#!/usr/bin/env python3
"""Publish the execute-test-case results tree to Yard without losing runs.

Yard's publish replaces a site's entire contents and has no undo, so publishing
a local directory that is missing runs the site already has would delete them.
This pulls the live site, copies across anything the results dir is missing,
rebuilds the index pages over the merged tree, and publishes the union. A results
dir that is empty or half-synced heals instead of clobbering.

    publish.py                 pull, rebuild, publish
    publish.py --dry-run       everything except the publish
    publish.py --no-pull       skip the pull; the only way to make a deletion stick
"""

from __future__ import annotations

import argparse
import json
import os
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path


DEFAULT_SITE = "adamp-testresults"
CONFIG_PATH = Path(
    os.environ.get("EXECUTE_TEST_CASE_CONFIG", "~/.claude/execute-test-case.json")
).expanduser()
BUILD_SCRIPT = Path(
    "~/.claude/skills/execute-test-case/scripts/testresults.py"
).expanduser()


def die(message: str) -> None:
    sys.exit(f"publish: {message}")


def run(argv: list[str], **kwargs) -> subprocess.CompletedProcess:
    try:
        return subprocess.run(argv, text=True, **kwargs)
    except FileNotFoundError:
        die(f"{argv[0]} not found on PATH")


# --------------------------------------------------------------------------- inputs


def load_config() -> dict:
    if not CONFIG_PATH.is_file():
        return {}
    try:
        loaded = json.loads(CONFIG_PATH.read_text(encoding="utf-8"))
    except json.JSONDecodeError:
        return {}
    return loaded if isinstance(loaded, dict) else {}


def resolve_results_dir(override: str | None) -> Path:
    source = override
    if not source:
        source = load_config().get("resultsDir")
        if not source:
            die(
                f"no results dir configured in {CONFIG_PATH}. Run a test case first, or pass "
                f"--results-dir"
            )
    resolved = Path(source).expanduser().resolve()
    if not resolved.is_dir():
        die(f"results dir does not exist: {resolved}")
    return resolved


def resolve_site(override: str | None) -> str:
    return override or load_config().get("yardSite") or DEFAULT_SITE


# --------------------------------------------------------------------------- checks


def require_login() -> str:
    """`yard whoami` reports a missing credential in its output, so check the email."""
    proc = run(["yard", "whoami", "--json"], capture_output=True)
    email = ""
    if proc.returncode == 0:
        try:
            email = str(json.loads(proc.stdout).get("email") or "")
        except json.JSONDecodeError:
            email = ""
    if not email:
        die("not signed in to Yard. Run `yard login` (it needs a browser) and try again")
    return email


def reject_symlinks(results_dir: Path) -> None:
    """Yard refuses a symlink rather than following it, so catch them before uploading."""
    links = sorted(p for p in results_dir.rglob("*") if p.is_symlink())
    if links:
        listing = "\n".join(f"  {p.relative_to(results_dir)}" for p in links)
        die(f"yard refuses symlinks; remove these first:\n{listing}")


def require_root_index(results_dir: Path) -> None:
    if not (results_dir / "index.html").is_file():
        die(
            f"no index.html at the root of {results_dir}; the build step should have written one"
        )


def tree_summary(results_dir: Path) -> tuple[int, int]:
    files = [p for p in results_dir.rglob("*") if p.is_file()]
    return len(files), sum(p.stat().st_size for p in files)


def run_slugs(results_dir: Path) -> set[str]:
    return {
        child.name
        for child in results_dir.iterdir()
        if child.is_dir() and not child.name.startswith((".", "_"))
    }


# --------------------------------------------------------------------------- steps


def pull(site: str, results_dir: Path) -> None:
    """Merge the live site into the results dir, adding only what is missing.

    `yard pull --force` documents itself as adding and replacing without deleting, but
    it actually fails on the first file that already exists ("file exists", exit 1). So
    pull into a scratch dir and copy across by hand. Local files always win: a run
    directory's name identifies it, so a name present in both places is the same run,
    and every index.html is regenerated by the build step afterwards regardless.
    """
    before = run_slugs(results_dir)
    scratch = Path(tempfile.mkdtemp(prefix="yard-pull-"))
    try:
        proc = run(["yard", "pull", site, str(scratch), "--force"], capture_output=True)
        if proc.returncode != 0:
            combined = ((proc.stdout or "") + (proc.stderr or "")).lower()
            # A site that has never been published has nothing to merge; that is fine.
            # Yard answers {"error":"not_found","message":"no such site"}.
            if any(token in combined for token in ("not_found", "no such site", "404")):
                print(f"  site {site} has not been published yet — nothing to merge")
                return
            sys.stderr.write((proc.stdout or "") + (proc.stderr or ""))
            die(f"yard pull failed (exit {proc.returncode})")

        added = 0
        for source in sorted(scratch.rglob("*")):
            if not source.is_file():
                continue
            target = results_dir / source.relative_to(scratch)
            if target.exists():
                continue
            target.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(source, target)
            added += 1
    finally:
        shutil.rmtree(scratch, ignore_errors=True)

    gained = sorted(run_slugs(results_dir) - before)
    if gained:
        print(f"  merged {len(gained)} run(s) back from the site:")
        for slug in gained:
            print(f"    + {slug}")
    if added:
        print(f"  restored {added} file(s) the site had and this machine did not")
    else:
        print("  nothing on the site was missing locally")


def build(results_dir: Path) -> None:
    if not BUILD_SCRIPT.is_file():
        die(
            f"build script not found at {BUILD_SCRIPT}; is the execute-test-case skill installed?"
        )
    proc = run(
        [
            "uv",
            "run",
            "--script",
            str(BUILD_SCRIPT),
            "build",
            "--results-dir",
            str(results_dir),
        ],
        capture_output=True,
    )
    if proc.returncode != 0:
        sys.stderr.write((proc.stdout or "") + (proc.stderr or ""))
        die(f"build failed (exit {proc.returncode})")
    wrote = sum(1 for line in proc.stdout.splitlines() if line.startswith("wrote "))
    print(f"  regenerated {wrote} index page(s)")


def publish(site: str, results_dir: Path) -> str:
    proc = run(
        ["yard", "publish", str(results_dir), site, "--yes", "--json"],
        capture_output=True,
    )
    if proc.returncode != 0:
        sys.stderr.write((proc.stdout or "") + (proc.stderr or ""))
        die(f"yard publish failed (exit {proc.returncode})")
    try:
        return str(json.loads(proc.stdout).get("url") or "")
    except json.JSONDecodeError:
        return proc.stdout.strip()


# --------------------------------------------------------------------------- main


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--site", help=f"Yard site id (default: {DEFAULT_SITE})")
    parser.add_argument("--results-dir", help="override the remembered results dir")
    parser.add_argument(
        "--no-pull",
        action="store_true",
        help="publish the local tree as-is; the only way to make a deleted run stay deleted",
    )
    parser.add_argument(
        "--dry-run", action="store_true", help="do everything except the publish"
    )
    args = parser.parse_args(argv)

    results_dir = resolve_results_dir(args.results_dir)
    site = resolve_site(args.site)
    email = require_login()
    print(f"site {site}, as {email}")
    print(f"results dir {results_dir}")

    if args.no_pull:
        print("pull: skipped (--no-pull) — runs only on the site will be DELETED")
    else:
        print("pull:")
        pull(site, results_dir)

    print("build:")
    build(results_dir)
    require_root_index(results_dir)
    reject_symlinks(results_dir)

    count, size = tree_summary(results_dir)
    runs = len(run_slugs(results_dir))
    print(f"ready: {runs} run(s), {count} files, {size / 1_048_576:.1f} MiB")

    if args.dry_run:
        print(
            f"dry run — not publishing. Would replace https://{site}.yard.roversvc.com/"
        )
        return 0

    print("publish:")
    url = publish(site, results_dir)
    print(f"  {url or f'https://{site}.yard.roversvc.com/'}")
    print(f"\nlocal: {(results_dir / 'index.html').as_uri()}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
